#Import Libraries

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

#Import Data

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/DhruvBhirud/datasets/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [6]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


#Missing Value

In [8]:
df.isna()

Unnamed: 0  Clothing ID    Age  Title  Review Text  Rating  \
0           False        False  False   True        False   False   
1           False        False  False   True        False   False   
2           False        False  False  False        False   False   
3           False        False  False  False        False   False   
4           False        False  False  False        False   False   
...           ...          ...    ...    ...          ...     ...   
23481       False        False  False  False        False   False   
23482       False        False  False  False        False   False   
23483       False        False  False  False        False   False   
23484       False        False  False  False        False   False   
23485       False        False  False  False        False   False   

       Recommended IND  Positive Feedback Count  Division Name  \
0                False                    False          False   
1                False                    False          False   
2                False                    False          False   
3                False                    False          False   
4                False                    False          False   
...                ...                      ...            ...   
23481            False                    False          False   
23482            False                    False          False   
23483            False                    False          False   
23484            False                    False          False   
23485            False                    False          False   

       Department Name  Class Name  
0                False       False  
1                False       False  
2                False       False  
3                False       False  
4                False       False  
...                ...         ...  
23481            False       False  
23482            False       False  
23483            False       False  
23484            False       False  
23485            False       False  

[23486 rows x 11 columns]

In [9]:
df[df['Review Text']==""]=np.NaN

In [10]:
df['Review Text'].fillna("No Review",inplace=True)

In [11]:
df.isna()

Unnamed: 0  Clothing ID    Age  Title  Review Text  Rating  \
0           False        False  False   True        False   False   
1           False        False  False   True        False   False   
2           False        False  False  False        False   False   
3           False        False  False  False        False   False   
4           False        False  False  False        False   False   
...           ...          ...    ...    ...          ...     ...   
23481       False        False  False  False        False   False   
23482       False        False  False  False        False   False   
23483       False        False  False  False        False   False   
23484       False        False  False  False        False   False   
23485       False        False  False  False        False   False   

       Recommended IND  Positive Feedback Count  Division Name  \
0                False                    False          False   
1                False                    False          False   
2                False                    False          False   
3                False                    False          False   
4                False                    False          False   
...                ...                      ...            ...   
23481            False                    False          False   
23482            False                    False          False   
23483            False                    False          False   
23484            False                    False          False   
23485            False                    False          False   

       Department Name  Class Name  
0                False       False  
1                False       False  
2                False       False  
3                False       False  
4                False       False  
...                ...         ...  
23481            False       False  
23482            False       False  
23483            False       False  
23484            False       False  
23485            False       False  

[23486 rows x 11 columns]

In [12]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

#Define y and X

In [13]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [14]:
X = df['Review Text']

In [15]:
y = df['Rating']

In [16]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

#Train Test Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y,random_state=202529)

#Get Feature Text Conversion to Tokens

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3),stop_words='english',max_features=5000)

In [21]:
X_train = cv.fit_transform(X_train)

In [22]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
X_test = cv.fit_transform(X_test)

In [25]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

#Get Model Train

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
model = MultinomialNB()

In [28]:
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [29]:
y_pred = model.predict(X_test)

In [30]:
y_pred

array([5., 1., 5., ..., 5., 5., 5.])

#Get Probability of Each Predict Class

In [31]:
model.predict_proba(X_test)

array([[0.14673183, 0.01682288, 0.22316232, 0.1265567 , 0.48672627],
       [0.37088178, 0.08348325, 0.20109113, 0.24375248, 0.10079135],
       [0.03328841, 0.0265961 , 0.08690435, 0.16889335, 0.68431779],
       ...,
       [0.06055559, 0.07797158, 0.32250694, 0.17860516, 0.36036074],
       [0.13679138, 0.16130378, 0.00983887, 0.19463949, 0.49742647],
       [0.13643228, 0.05019723, 0.07139988, 0.33614366, 0.40582696]])

#Get Model Evaluation

In [32]:
from sklearn.metrics import confusion_matrix, classification_report

In [33]:
print(confusion_matrix(y_test, y_pred))

[[  26   21   37   46  123]
 [  49   51   73   79  218]
 [ 128   75  135  168  355]
 [ 188  110  208  328  689]
 [ 409  211  429  786 2104]]


In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.10      0.05       253
         2.0       0.11      0.11      0.11       470
         3.0       0.15      0.16      0.15       861
         4.0       0.23      0.22      0.22      1523
         5.0       0.60      0.53      0.57      3939

    accuracy                           0.38      7046
   macro avg       0.23      0.22      0.22      7046
weighted avg       0.41      0.38      0.39      7046



#Recategories Rating as Poor 0 and Good 1

In [35]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

Rerating as 1,2,3 as 0 and 4,5 as 1

In [36]:
df.replace({'Rating': {1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [37]:
y=df['Rating']

In [38]:
X=df['Review Text']

#Train Test Split

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.7,random_state=202529)

#Get Feature Text Conversion to Tokens

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv = CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [43]:
X_train = cv.fit_transform(X_train)

In [44]:
X_test = cv.fit_transform(X_test)

#Get Model ReTrain

In [45]:
from sklearn.naive_bayes import MultinomialNB

In [46]:
model = MultinomialNB()

In [47]:
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [48]:
y_pred = model.predict(X_test)

In [49]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

#Get Model Evaluation

In [50]:
from sklearn.metrics import confusion_matrix, classification_report

In [51]:
print(confusion_matrix(y_test,y_pred))

[[ 346 1184]
 [1046 4470]]


In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.25      0.23      0.24      1530
         1.0       0.79      0.81      0.80      5516

    accuracy                           0.68      7046
   macro avg       0.52      0.52      0.52      7046
weighted avg       0.67      0.68      0.68      7046

